config/routes.rb
Rails.application.routes.draw do
  resources :reminders
  get 'welcome_page/welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome_page#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reminder.rb
class Reminder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: %i[ show edit update destroy ]

  # GET /reminders or /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1 or /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders or /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to reminder_url(@reminder), notice: "Reminder was successfully created." }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1 or /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to reminder_url(@reminder), notice: "Reminder was successfully updated." }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1 or /reminders/1.json
  def destroy
    @reminder.destroy

    respond_to do |format|
      format.html { redirect_to reminders_url, notice: "Reminder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_params
      params.require(:reminder).permit(:text)
    end
end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsElasticBeanstalk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder) do |form| %>
  <% if reminder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% reminder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/_reminder.html.erb
<div id="<%= dom_id reminder %>">
  <p>
    <strong>Text:</strong>
    <%= reminder.text %>
  </p>

</div>

app/views/reminders/edit.html.erb
<h1>Editing reminder</h1>

<%= render "form", reminder: @reminder %>

<br>

<div>
  <%= link_to "Show this reminder", @reminder %> |
  <%= link_to "Back to reminders", reminders_path %>
</div>

app/views/reminders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reminders</h1>

<div id="reminders">
  <% @reminders.each do |reminder| %>
    <%= render reminder %>
    <p>
      <%= link_to "Show this reminder", reminder %>
    </p>
  <% end %>
</div>

<%= link_to "New reminder", new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New reminder</h1>

<%= render "form", reminder: @reminder %>

<br>

<div>
  <%= link_to "Back to reminders", reminders_path %>
</div>

app/views/reminders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reminder %>

<div>
  <%= link_to "Edit this reminder", edit_reminder_path(@reminder) %> |
  <%= link_to "Back to reminders", reminders_path %>

  <%= button_to "Destroy this reminder", @reminder, method: :delete %>
</div>

app/views/welcome_page/welcome.html.erb
<h1>Welcome!</h1>
<p>This is the front page of my first Rails application on Elastic Beanstalk.</p>
<p>It has been successfully deployed via Github Actions!</p>